# Generated by Django 4.2.9 on 2024-01-17 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iqf_event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='phone',
        ),
    ]
