# Generated by Django 4.2.9 on 2024-01-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqf_event', '0002_remove_registration_cpf_remove_registration_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='cpf',
            field=models.CharField(default=0, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='full_name',
            field=models.CharField(default='Robertinho de jeus', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(default='11947292289', max_length=15),
            preserve_default=False,
        ),
    ]
