# Generated by Django 4.2.9 on 2024-01-17 23:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iqf_event', '0003_registration_cpf_registration_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='data_inscricao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
