# Generated by Django 4.2.9 on 2024-01-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqf_event', '0004_registration_data_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='presence',
            field=models.CharField(default='Ausente', max_length=10),
        ),
    ]
