# Generated by Django 4.2.9 on 2024-01-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqf_event', '0006_registration_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='cargo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
